### ISSUE TITLE
Sigh failing on MacBook with URL error.

### ISSUE THREAD

**Issue by yuinchien** [PolymerLabs/arcs#1063]
Consulting with @shaper and filing issue to track.

Attempting to run `./tools/sigh` produces:

```
yuin-macbookpro:arcs yuin$ ./tools/sigh
😌
🙋 check
🙆 check
🙋 peg
Skipping step; 'runtime/build/manifest-parser.js' is up-to-date
🙆 peg
🙋 railroad
Skipping step; 'manifest-railroad.html' is up-to-date
🙆 railroad
🙋 test
(node:30258) ExperimentalWarning: The ESM module loader is experimental.
    at startup (bootstrap_node.js:105:15)
    at bootstrap_node.js:666:3
{ TypeError [ERR_INVALID_URL]: Invalid URL: /var/folders/22/1mwk38yn1j9f6kzpq9j4sx1r004bmn/T/sigh-V49xVD/runner.js
    at onParseError (internal/url.js:217:17)
    at parse (internal/url.js:226:3)
    at new URL (internal/url.js:309:5)
    at resolve (file:///Users/yuin/Dev/arcs/tools/custom-loader.mjs:21:20)
    at Loader.resolve (internal/loader/Loader.js:50:18)
    at Loader.getModuleJob (internal/loader/Loader.js:82:40)
    at Loader.import (internal/loader/Loader.js:68:28)
    at internalESModule.loaderPromise.then (module.js:460:27)
    at <anonymous>
  input: '/var/folders/22/1mwk38yn1j9f6kzpq9j4sx1r004bmn/T/sigh-V49xVD/runner.js' }
🙅 test
😱
```

Node and npm versions:

```
yuin-macbookpro:arcs yuin$ npm -v
5.8.0
yuin-macbookpro:arcs yuin$ node -v
v9.9.0
```

This is at ToT with no modifications after running `npm install`. We started hacking the urls built in custom-loader to prepend 'file://localhost/' and seemed to make it farther but then experienced new errors.

**Comment by shaper** [comment]
Potentially fixed by https://github.com/PolymerLabs/arcs/pull/1066#pullrequestreview-107507355
