### ISSUE TITLE
Selenium tests appear to be broken.

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#1145]
Went red with this build https://travis-ci.org/PolymerLabs/arcs/builds/363205736

But appear red at prior commits as well, can repro locally.

**Comment by shaper** [comment]
Green as of https://travis-ci.org/PolymerLabs/arcs/builds/363303494

**Comment by smalls** [comment]
It's been unhappy again :/

**Comment by smalls** [comment]
It's become flappier.. new failures as of https://travis-ci.org/PolymerLabs/arcs/builds/364866941:

```
[chrome #0-0] Arcs demos
[chrome #0-0]   1) can book a restaurant
[chrome #0-0]   2) can buy gifts
[chrome #0-0]
[chrome #0-0] Arcs system
[chrome #0-0]   3) can load with global manifests
[chrome #0-0]
[chrome #0-0]
[chrome #0-0] 3 failing (11s)
[chrome #0-0]
[chrome #0-0] 1) Arcs demos can book a restaurant:
[chrome #0-0] selectors #webtest-title never selected anything
[chrome #0-0] Error: selectors #webtest-title never selected anything
[chrome #0-0]     at elementIdDisplayed("0.9085300539265895-33") - index.js:312:3
[chrome #0-0]
[chrome #0-0] 2) Arcs demos can buy gifts:
[chrome #0-0] stale element reference: element is not attached to the page document
[chrome #0-0] Error: An element command failed because the referenced element is no longer attached to the DOM.
[chrome #0-0]     at elements("<app-shell>") - isVisible.js:54:17
[chrome #0-0]     at isVisible("<app-shell>") - waitForVisible.js:73:22
[chrome #0-0]
[chrome #0-0] 3) Arcs system can load with global manifests:
[chrome #0-0] unknown error: pierceShadows is not defined
[chrome #0-0] Error: An unknown server-side error occurred while processing the command.
[chrome #0-0]     at elementIdDisplayed("0.07993425985303992-1") - isVisible.js:71:55
```

**Comment by smalls** [comment]
Not fixed yet!

```
[chrome #0-0] Running: chrome
[chrome #0-0]
[chrome #0-0] Arcs demos
[chrome #0-0]   1) can book a restaurant
[chrome #0-0]   ✓ can buy gifts
[chrome #0-0]
[chrome #0-0] Arcs system
[chrome #0-0]   ✓ can load with global manifests
[chrome #0-0]
[chrome #0-0]
[chrome #0-0] 2 passing (31s)
[chrome #0-0] 1 failing
[chrome #0-0]
[chrome #0-0] 1) Arcs demos can book a restaurant:
[chrome #0-0] 'Find restaurants near Selenium\'s location.' == 'Select a time from your calendar, Table for 2 available at 19:00, and find restaurants near Selenium\'s location.'
[chrome #0-0] AssertionError [ERR_ASSERTION]: 'Find restaurants near Selenium\'s location.' == 'Select a time from your calendar, Table for 2 available at 19:00, and find restaurants near Selenium\'s location.'
[chrome #0-0]     at getOrCompare (/home/travis/build/PolymerLabs/arcs/shell/test/specs/demo-tests.js:436:18)
[chrome #0-0]     at testAroundRefresh (/home/travis/build/PolymerLabs/arcs/shell/test/specs/demo-tests.js:450:3)
[chrome #0-0]     at Context.<anonymous> (/home/travis/build/PolymerLabs/arcs/shell/test/specs/demo-tests.js:478:5)
[chrome #0-0]     at new Promise (<anonymous>)
[chrome #0-0]     at new F (/home/travis/build/PolymerLabs/arcs/node_modules/core-js/library/modules/_export.js:35:28)
[chrome #0-0]
```

**Comment by smalls** [comment]
Still at least an issue:

```
[chrome #0-0] Session ID: 1a1986c5aaa58c2a6445341df8fd1ebc
[chrome #0-0] Spec: /home/travis/build/PolymerLabs/arcs/shell/test/specs/demo-tests.js
[chrome #0-0] Running: chrome
[chrome #0-0]
[chrome #0-0] Arcs demos
[chrome #0-0]   1) can book a restaurant
[chrome #0-0]   ✓ can buy gifts
[chrome #0-0]
[chrome #0-0] Arcs system
[chrome #0-0]   ✓ can load with global manifests
[chrome #0-0]
[chrome #0-0]
[chrome #0-0] 2 passing (29s)
[chrome #0-0] 1 failing
[chrome #0-0]
[chrome #0-0] 1) Arcs demos can book a restaurant:
[chrome #0-0] unknown error: Element <dancing-dots slot="toast-header">...</dancing-dots> is not clickable at point (392, 527). Other element would receive the click: <input placeholder="Search">
[chrome #0-0] Error: An unknown server-side error occurred while processing the command.
[chrome #0-0]     at elementIdClick("0.47927258616524493-3") - index.js:312:3
[chrome #0-0]
```

**Comment by smalls** [comment]
Hmm, I'm not sure about that one. My guess is that what's happened is that the drawer happened to be sliding when we made the initial selection, and by the time the click happened the drawer had opened.

Hmm. I think this is a race condition - there's a lag between selecting the element and clicking it, and both of those cross from the test driver into the browser so it's enough time that the animation can progress to the point where a different element is at those coordinates.

One option would be to remove that boundary jump - to select & click in the same call to the browser context. I'd like to see this fail a few more times before doing that, though.

The code in question (from `demo-tests.js`, line ~203 in `openSuggestionDrawer()`:

```
    const dancingDots = dancingDotsElement();
    console.log(`click: suggestions drawer closed`);
    browser.elementIdClick(dancingDots.value.ELEMENT);
```
