### ISSUE TITLE
Mic input throws start errors with Chromoting.

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#1183]
When I chromote into my workstation and do anything in launcher where I press the shift key my console log fills with mic input errors, sample below. It's not a big deal but seems worth addressing in some manner. It's annoying for development.

```
:9119/arcs/shell/components/xen/xen-state.js:120 DOMException: Failed to execute 'start' on 'SpeechRecognition': recognition has already started.
    at HTMLElement._start (http://localhost:9119/arcs/shell/components/mic-input.js:60:21)
    at HTMLElement._update (http://localhost:9119/arcs/shell/components/mic-input.js:26:12)
    at HTMLElement._doUpdate (http://localhost:9119/arcs/shell/components/xen/xen-base.js:36:10)
    at HTMLElement._validate (http://localhost:9119/arcs/shell/components/xen/xen-state.js:117:14)
```

**Comment by shaper** [comment]
Duplicate of https://github.com/PolymerLabs/arcs/issues/1490
