### ISSUE TITLE
flaky selenium tests

### ISSUE THREAD

**Issue by smalls** [PolymerLabs/arcs#1189]
The tests flap, but I believe for the most part pretty slowly. I'd like some more data about how they're flapping and what sort of errors we're seeing, so I'm going to track the issue and record that data here.

Errors:

* the suggestions drawer isn't registering with state 'open' after a click
Occurences: [2018.04.13](https://travis-ci.org/PolymerLabs/arcs/builds/366212740), [2018.04.13](https://travis-ci.org/PolymerLabs/arcs/builds/366225425), [2018.04.13](https://travis-ci.org/PolymerLabs/arcs/builds/366333566), [2018.04.15](https://travis-ci.org/PolymerLabs/arcs/builds/366950317), [2018.04.16](https://travis-ci.org/PolymerLabs/arcs/builds/367007202)
Full error text:
```
[chrome #0-0] 1) Arcs demos can buy gifts:
[chrome #0-0] the suggestions drawer isn't registering with state 'open' after a click
[chrome #0-0] Error: the suggestions drawer isn't registering with state 'open' after a click
[chrome #0-0]     at elementIdAttribute("0.03309241717119238-2", "open") - index.js:312:3
```

* Dancing dots not clickable at point
Occurences: 2018.04.13, [2018.04.13](https://travis-ci.org/PolymerLabs/arcs/builds/366338022)
Full error text:
```
[chrome #0-0] 1) Arcs demos can book a restaurant:
[chrome #0-0] unknown error: Element <dancing-dots slot="toast-header">...</dancing-dots> is not clickable at point (392, 572). Other element would receive the click: <input placeholder="Search">
[chrome #0-0] Error: An unknown server-side error occurred while processing the command.
[chrome #0-0]     at elementIdClick("0.35860659927616667-3") - index.js:312:3
```

**Comment by smalls** [comment]
#1207 fixes the following issue (by disabling the specific check that was failing):

* Mismatch in suggestions over refresh
Occurences: [2018.04.13](https://travis-ci.org/PolymerLabs/arcs/builds/366230127), [2018.04.15](https://travis-ci.org/PolymerLabs/arcs/builds/367007202), [2018.04.17](https://travis-ci.org/PolymerLabs/arcs/builds/367903489), [2018.04.18](https://travis-ci.org/PolymerLabs/arcs/builds/368018464)
Full error text:
```
[chrome #0-0] 'Find restaurants near Selenium\'s location.' == 'Select a time from your calendar, Table for 2 available at 18:30, and find restaurants near Selenium\'s location.'
[chrome #0-0] AssertionError [ERR_ASSERTION]: 'Find restaurants near Selenium\'s location.' == 'Select a time from your calendar, Table for 2 available at 18:30, and find restaurants near Selenium\'s location.'
[chrome #0-0]     at getOrCompare (/home/travis/build/PolymerLabs/arcs/shell/test/specs/demo-tests.js:436:18)
[chrome #0-0]     at testAroundRefresh (/home/travis/build/PolymerLabs/arcs/shell/test/specs/demo-tests.js:450:3)
[chrome #0-0]     at Context.<anonymous> (/home/travis/build/PolymerLabs/arcs/shell/test/specs/demo-tests.js:478:5)
[chrome #0-0]     at new Promise (<anonymous>)
[chrome #0-0]     at new F (/home/travis/build/PolymerLabs/arcs/node_modules/core-js/library/modules/_export.js:35:28)
```

**Comment by smalls** [comment]
I don't think this issue is tracking anything worthwhile (currently). As far as I can tell the tests have been more or less stable except when bugs are introduced.

Please re-open if I'm wrong!
