### ISSUE TITLE
Duplicate particle test failures

### ISSUE THREAD

**Issue by lindner** [PolymerLabs/arcs#1466]
Environment:
- macOS 10.13.4
- node 10.4.0, npm 6.1.0

I am still seeing two failures on a fresh checkout running `./tools/sigh`

```
2 failing

  1) recipe descriptions test fails generating recipe description with duplicate particles:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

  2) recipe descriptions test generates recipe description with duplicate particles:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

The following output is generated:

```
Exception in particle code
 TypeError [ERR_INVALID_ARG_TYPE]: The "options.filename" property must be of type string. Received type object
    at new Script (vm.js:57:13)
    at StubLoader.requireParticle (file:///Users/plindner/arcs/runtime/loader.js:78:18)
Exception in particle code
 TypeError [ERR_INVALID_ARG_TYPE]: The "options.filename" property must be of type string. Received type object
    at new Script (vm.js:57:13)
    at StubLoader.requireParticle (file:///Users/plindner/arcs/runtime/loader.js:78:18)
    1) fails generating recipe description with duplicate particles
Exception in particle code
 TypeError [ERR_INVALID_ARG_TYPE]: The "options.filename" property must be of type string. Received type object
    at new Script (vm.js:57:13)
    at StubLoader.requireParticle (file:///Users/plindner/arcs/runtime/loader.js:78:18)
Exception in particle code
 TypeError [ERR_INVALID_ARG_TYPE]: The "options.filename" property must be of type string. Received type object
    at new Script (vm.js:57:13)
    at StubLoader.requireParticle (file:///Users/plindner/arcs/runtime/loader.js:78:18)
Exception in particle code
 TypeError [ERR_INVALID_ARG_TYPE]: The "options.filename" property must be of type string. Received type object
    at new Script (vm.js:57:13)
    at StubLoader.requireParticle (file:///Users/plindner/arcs/runtime/loader.js:78:18)
    2) generates recipe description with duplicate particles
```

Digging in a little deeper it appears that the following code is failing due to a null filename in `runtime/loader.js` when called by 

```javascript
async requireParticle(fileName) {
    let src = await this.loadResource(fileName);
    // Note. This is not real isolation.
    let script = new vm.Script(src, {filename: fileName, displayErrors: true});
    let result = [];
```

Adding an assert to catch empty fileName results in a stack trace that looks like this:

```
AssertionError [ERR_ASSERTION]: false == true
    at StubLoader.loadParticleClass (file:///Users/plindner/arcs/runtime/loader.js:70:5)
    at InnerPEC._instantiateParticle (file:///Users/plindner/arcs/runtime/inner-PEC.js:193:36)
    at PECInnerPort.InnerPEC._apiPort.onInstantiateParticle (file:///Users/plindner/arcs/runtime/inner-PEC.js:64:37)
    at PECInnerPort._handle (file:///Users/plindner/arcs/runtime/api-channel.js:177:35)
    at MessagePort.APIPort._port.onmessage [as _onmessage] (file:///Users/plindner/arcs/runtime/api-channel.js:89:44)
    at MessageChannel._post (file:///Users/plindner/arcs/runtime/message-channel.js:52:31)
```

Will try to find some time to diagnose this week; but if anyone has ideas I'd love to know more.

**Comment by lindner** [comment]
Oh and I also bisected and the errors I see in my environment go all the way back to the original addition of the duplicated particle test by @mmandlis in 10e7b84

**Comment by sjmiles** [comment]
IIUC, these test have to pass on Travis/AppVeyor or those CI tools yell at us. 

That would imply a difference in runtime environment, yes?

Maybe I'm not understanding something.

**Comment by mykmartin** [comment]
@lindner, are you still seeing this problem? I can't repro on Linux (node 9.4.0, npm 5.7.1)

**Comment by shaper** [comment]
I repro'd on Linux just now after updating via `nvm install 10`, which produced `Now using node v10.4.1 (npm v6.1.0)`.

**Comment by shaper** [comment]
Node 10 is interesting in part due to performance changes per https://v8project.blogspot.com/2018/06/concurrent-marking.html

> Concurrent marking is enabled by default in Chrome 64 and Node.js v10.

**Comment by shaper** [comment]
I started looking at this further so I'm picking up the issue.
