### ISSUE TITLE
Muxer problem (maybe?) with Reservations 

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#2581]
Requires https://github.com/sjmiles/arcs/tree/misc-2019 for the test particles.

Steps:
1. Launcher
2. Choose `Find restaurants...`
3. Choose `... and make reservations`

Problems:
1. ReservationAnnotation particles are not rendering (should be visible under each restaurant Tile)
2. Usually I get this exception (DevTools):
![image](https://user-images.githubusercontent.com/98045/51070139-cef4e100-15f0-11e9-9c88-3c7cf05b65af.png)
3. On refresh, tiles don't render and there are cascading failures:
![image](https://user-images.githubusercontent.com/98045/51070143-0b284180-15f1-11e9-8ec9-b22eb3545442.png)

**Comment by mmandlis** [comment]
The very top exception is issue #2576 and fixed by #2588.

Once that is fixed, for `?user=scott&arc=scott--LVuNaW4SK6JlEPe8VYm` i'm getting: 
```
browser-loader.js:67 Uncaught (in promise) DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:8001/arcs-1/particles/Events/source/Calendar.js' failed to load.
    at BrowserLoader.requireParticle (http://localhost:8001/arcs-1/shells/lib/build/worker.js:6930:5)
    at BrowserLoader.loadParticleClass (http://localhost:8001/arcs-1/shells/lib/build/worker.js:3370:34)
    at ParticleExecutionContext._instantiateParticle (http://localhost:8001/arcs-1/shells/lib/build/worker.js:2551:41)
    at Object.onInstantiateParticle (http://localhost:8001/arcs-1/shells/lib/build/worker.js:2407:28)
    at Object.before (http://localhost:8001/arcs-1/shells/lib/build/worker.js:2149:50)
    at Object._processMessage (http://localhost:8001/arcs-1/shells/lib/build/worker.js:2016:44)
    at MessagePort.APIPort._port.onmessage (http://localhost:8001/arcs-1/shells/lib/build/worker.js:1998:50)
```
And I think the Calendar particle is in fact missing. @sjmiles Could you, maybe merge it, so we can debug the rest of the issue.

**Comment by sjmiles** [comment]
Did you pull the branch as per instructions above? Or are you asking me to push this stuff into main?

**Comment by mmandlis** [comment]
> Did you pull the branch as per instructions above? Or are you asking me to push this stuff into main?

ops sorry, i tried it with the wrong branch. will retry now.

**Comment by sjmiles** [comment]
Multiplexer-internal recipes were not resolving (due to missing `descriptions` handle) and the logging was squelched due to bugs. Both problems are resolved now.
