### ISSUE TITLE
Firebase manual tests failing

### ISSUE THREAD

**Issue by lindner** [PolymerLabs/arcs#3068]
Output on clean client looks like:

```
 23 passing (35s)
  2 failing

  1) firebase
       variable
         resolves concurrent set:
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/plindner/arcs/particles/build/runtime/manual_tests/firebase-tests.js)


  2) firebase
       big collection
         serialization roundtrip re-attaches to the same firebase stores:

      AssertionError: expected 'v1' to equal 'v4'
      + expected - actual

      -v1
      +v4

      at Context.it (file:///Users/plindner/arcs/particles/src/runtime/manual_tests/firebase-tests.ts:769:14)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by lindner** [comment]
This is caused by 17f565f70f3699c574707cafc2212be2d7160d23

@shans should we revert the firebase change for now?  Also affecting @sjmiles

**Comment by sjmiles** [comment]
See also #3040

**Comment by shans** [comment]
Yes let's revert this patch for now.
