### ISSUE TITLE
can't use props (or entities contained within props) directly in a return from render

### ISSUE THREAD

**Issue by smalls** [PolymerLabs/arcs#499]
You'll get an error like below. Instead, you need to at least make a shallow copy of the entities.

We could fix this or make the error better.

DOMException: Failed to execute 'postMessage' on 'MessagePort': [object Object] could not be cloned.
    at PECInnerPort.(anonymous function).args [as Render] (https://polymerlabs.github.io/arcs-cdn/dev/lib/worker-entry-cdn.js:23451:18)
    at Slotlet.render (https://polymerlabs.github.io/arcs-cdn/dev/lib/worker-entry-cdn.js:14212:30)
    at Object.render (https://polymerlabs.github.io/arcs-cdn/dev/lib/worker-entry-cdn.js:13563:12)
    at config.slotNames.forEach.s (https://polymerlabs.github.io/arcs-cdn/dev/lib/worker-entry-cdn.js:13547:45)
    at Array.forEach (<anonymous>)
    at Object._update (https://polymerlabs.github.io/arcs-cdn/dev/lib/worker-entry-cdn.js:13547:27)
    at Object._validate (https://polymerlabs.github.io/arcs-cdn/dev/lib/worker-entry-cdn.js:23649:14)
    at <anonymous>

**Comment by shaper** [comment]
Needs repro attempt, not sure if still an issue.
