### ISSUE TITLE
Flaky test in particle-shape-loading-with-slots

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#533]
`multiplex recipe with slots (init context later)` failing with timeout reproducibly at ToT for me. It passes maybe 1 / 5.

Error log:

Exception in particle code
 { AssertionError: Got a renderSlot from SingleSlotParticle:annotation (content types: template, model), but not expecting anything further.
    at MockSlotComposer.renderSlot (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/test/mock-slot-composer.js:94:5)
    at PECOuterPort.OuterPEC._apiPort.onRender (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/outer-PEC.js:31:27)
    at PECOuterPort._handle (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/api-channel.js:171:49)
    at MessagePort.APIPort._port.onmessage [as _onmessage] (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/api-channel.js:80:44)
    at MessageChannel._post (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/message-channel.js:50:31)
    at MessagePort.postMessage (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/message-channel.js:21:19)
    at PECInnerPort.(anonymous function).args [as Render] (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/api-channel.js:195:18)
    at Slotlet.render (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/inner-PEC.js:160:30)
    at SingleSlotParticle.render (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/dom-particle.js:121:12)
    at PECInnerPort.InnerPEC._apiPort.onStartRender (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/inner-PEC.js:186:16)
    at PECInnerPort._handle (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/api-channel.js:171:49)
    at MessagePort.APIPort._port.onmessage [as _onmessage] (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/api-channel.js:80:44)
    at MessageChannel._post (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/message-channel.js:50:31)
    at MessagePort.postMessage (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/message-channel.js:21:19)
    at PECOuterPort.(anonymous function).args [as StartRender] (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/api-channel.js:195:18)
    at OuterPEC.startRender (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/outer-PEC.js:150:19)
    at MockSlot.startRender (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/slot.js:55:14)
    at MockSlot.setContext (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/slot.js:43:14)
    at Context.it (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/test/particle-shape-loading-with-slots-test.js:121:28)
    at <anonymous>
  message: 'Got a renderSlot from SingleSlotParticle:annotation (content types: template, model), but not expecting anything further.',
  showDiff: false,
  actual: null,
  expected: undefined }
Exception in particle code
 { AssertionError: Got a renderSlot from SingleSlotParticle:annotation (content types: template, model), but not expecting anything further.
    at MockSlotComposer.renderSlot (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/test/mock-slot-composer.js:94:5)
    at PECOuterPort.OuterPEC._apiPort.onRender (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/outer-PEC.js:31:27)
    at PECOuterPort._handle (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/api-channel.js:171:49)
    at MessagePort.APIPort._port.onmessage [as _onmessage] (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/api-channel.js:80:44)
    at MessageChannel._post (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/message-channel.js:50:31)
    at MessagePort.postMessage (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/message-channel.js:21:19)
    at PECInnerPort.(anonymous function).args [as Render] (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/api-channel.js:195:18)
    at Slotlet.render (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/inner-PEC.js:160:30)
    at SingleSlotParticle.render (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/dom-particle.js:121:12)
    at PECInnerPort.InnerPEC._apiPort.onStartRender (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/inner-PEC.js:186:16)
    at PECInnerPort._handle (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/api-channel.js:171:49)
    at MessagePort.APIPort._port.onmessage [as _onmessage] (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/api-channel.js:80:44)
    at MessageChannel._post (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/message-channel.js:50:31)
    at MessagePort.postMessage (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/message-channel.js:21:19)
    at PECOuterPort.(anonymous function).args [as StartRender] (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/api-channel.js:195:18)
    at OuterPEC.startRender (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/outer-PEC.js:150:19)
    at MockSlot.startRender (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/slot.js:55:14)
    at MockSlot.setContext (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/slot.js:43:14)
    at Context.it (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs/runtime/test/particle-shape-loading-with-slots-test.js:121:28)
    at <anonymous>
  message: 'Got a renderSlot from SingleSlotParticle:annotation (content types: template, model), but not expecting anything further.',
  showDiff: false,
  actual: null,
  expected: undefined }
    1) multiplex recipe with slots (init context later)

  1 passing (2s)
  1 failing

  1) particle-shape-loading-with-slots
       multiplex recipe with slots (init context later):
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

**Comment by shaper** [comment]
FYI @mmandlis since this looks like it may relate to transformation bits that she worked on recently.

**Comment by mmandlis** [comment]
@shans - is it the same error you were seeing too?

**Comment by shaper** [comment]
Interestingly `mocha test/particle-shape-loading-with-slots-test.js --grep 'later'` seems like it always passes. So it may be an interaction with the other test variant that runs earlier in the file. Maybe timing related due to setInterval? Can we rework easily to not use setInterval?

**Comment by shaper** [comment]
I haven't seen this flaking in a long time. Closing presuming fixed, please reopen if I'm off base.

**Comment by mmandlis** [comment]
Update:
Now the "multiplex recipe with slots" is occasionally failing with:
```
✓ multiplex recipe with slots (104ms)
(node:14503) AssertionError: Got a renderSlot from MultiplexSlotsParticle:annotationsSet (content types: model), but not expecting anything further.
    at MockSlotComposer.renderSlot (file:///Users/mmandlis/arcs/arcs/runtime/test/mock-slot-composer.js:136:5)
    at PECOuterPort.OuterPEC._apiPort.onRender (file:///Users/mmandlis/arcs/arcs/runtime/outer-PEC.js:31:27)
    at PECOuterPort._handle (file:///Users/mmandlis/arcs/arcs/runtime/api-channel.js:182:35)
    at MessagePort.APIPort._port.onmessage [as _onmessage] (file:///Users/mmandlis/arcs/arcs/runtime/api-channel.js:89:44)
    at MessageChannel._post (file:///Users/mmandlis/arcs/arcs/runtime/message-channel.js:52:31)
    at <anonymous>
```
