### ISSUE TITLE
demo-flow-test exhibits flakiness in some environments.

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#780]
@mmandlis unable to repro on Mac laptop, but I can repro maybe 3 / 10 times on my Linux workstation and Pixelbook.

Issue exists synced to https://github.com/PolymerLabs/arcs/commit/c92bbf7025a31e6004cb16077d0c3d81390ed739 

Repro via:

'for i in `seq 10`; do ./tools/sigh test --grep='demo'; done'

Running browser demo locally also shows exception loading a recipe, unsure if related. Exception as:

```
Uncaught (in promise) Error: Missing thing undefined
    at assert (http://localhost:5001/runtime/browser/build/worker-entry.js:85:11)
    at ThingMapper.identifierForThing (http://localhost:5001/runtime/browser/build/worker-entry.js:2485:100)
    at Object.convert (http://localhost:5001/runtime/browser/build/worker-entry.js:2521:34)
    at PECInnerPort._processArguments (http://localhost:5001/runtime/browser/build/worker-entry.js:2607:55)
    at PECInnerPort.(anonymous function).args [as ArcMapHandle] (http://localhost:5001/runtime/browser/build/worker-entry.js:2620:56)
    at Promise (http://localhost:5001/runtime/browser/build/worker-entry.js:1926:24)
    at new Promise (<anonymous>)
    at Object.mapHandle (http://localhost:5001/runtime/browser/build/worker-entry.js:1925:16)
    at Multiplexer.setViews (http://localhost:5001/shell/artifacts/Common/source/Multiplexer.js:33:49)
    at <anonymous>
assert @ worker-entry.js:85
identifierForThing @ worker-entry.js:2485
convert @ worker-entry.js:2521
_processArguments @ worker-entry.js:2607
(anonymous function).args @ worker-entry.js:2620
Promise @ worker-entry.js:1926
mapHandle @ worker-entry.js:1925
setViews @ Multiplexer.js:33
```

And I believe it's for this recipe:

```
recipe
  create as view0 // Product List
  copy 'manifest:browser/demo/recipes.manifest:view0' #shortlist as view1 // Product List
  map 'manifest:browser/demo/recipes.manifest:view1' #wishlist as view2 // Product List
  create as view3 // Description List
  map 'manifest:browser/demo/recipes.manifest::7:immediateAlsoOn' as view4 // SHAAAAPE
  slot 'rootslotid-root' as slot3
  Chooser as particle0
    choices <- view0
    resultList = view1
    consume action as slot0
      provide annotation as slot1
  Multiplexer2 as particle1
    hostedParticle host view4
    list <- view1
    others <- view0
    consume annotation as slot2
  Recommend as particle2
    known <- view1
    population <- view2
    recommendations -> view0
  ShowItems as particle3
    descriptions -> view3
    list <- view1
    consume root as slot3
      provide action as slot0
      provide annotation as slot2
      provide postamble as slot4
      provide preamble as slot5"
```

**Comment by shaper** [comment]
Can't repro synced to https://github.com/PolymerLabs/arcs/commit/0d07e6eb8ab34339a9ad595714b1ff3f65c94bec

@mmandlis it looks like this may be the breaking change from local repro exploration: https://github.com/PolymerLabs/arcs/commit/ddb9a13c6b0c77d480e9507e7a9392b27ba56304

but this is surprising since that commit is explicitly aiming to de-flake the test.

**Comment by mmandlis** [comment]
Can you, please, uncomment the log in mock-slot-composer.js ln 135
```
//    console.log(`renderSlot ${particle.name}:${slotName}`, Object.keys(content).join(', '));
```
and add here the log of a failing run?

**Comment by shaper** [comment]
Failing run:

```
renderSlot ShowItems:root template
renderSlot ShowItems:root 
renderSlot ShowItems:root model
renderSlot Chooser:action template, model
renderSlot AlsoOn:annotation template, model
renderSlot Multiplexer2:annotation template, model
renderSlot AlsoOn:annotation template, model
renderSlot Multiplexer2:annotation model
renderSlot AlsoOn:annotation template, model
renderSlot Multiplexer2:annotation model
```

Successful run:

```
renderSlot ShowItems:root template
renderSlot ShowItems:root 
renderSlot ShowItems:root model
renderSlot Chooser:action template, model
renderSlot AlsoOn:annotation template, model
renderSlot Multiplexer2:annotation template, model
renderSlot AlsoOn:annotation template, model
renderSlot Multiplexer2:annotation model
renderSlot AlsoOn:annotation template, model
renderSlot Multiplexer2:annotation model
renderSlot Chooser:action model
renderSlot ShowItems:root model
renderSlot Multiplexer2:annotation model
renderSlot AlsoOn:annotation model
renderSlot Multiplexer2:annotation model
```

**Comment by mmandlis** [comment]
Closing this, Walter, please, reopen if you experience it again.
