### ISSUE TITLE
Multiplexer error: Missing thing undefined

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#801]
I mentioned this the other day and it looks like it may be Multiplexer related so passing to @mmandlis for consideration and FYI @sjmiles 

On visiting launcher I get an error as:

```
Uncaught (in promise) Error: Missing thing undefined
    at assert (http://localhost:8000/arcs/shell/build/worker-entry-cdn.js:85:11)
    at ThingMapper.identifierForThing (http://localhost:8000/arcs/shell/build/worker-entry-cdn.js:2381:100)
    at Object.convert (http://localhost:8000/arcs/shell/build/worker-entry-cdn.js:2417:34)
    at PECInnerPort._processArguments (http://localhost:8000/arcs/shell/build/worker-entry-cdn.js:2503:55)
    at PECInnerPort.(anonymous function).args [as ArcMapHandle] (http://localhost:8000/arcs/shell/build/worker-entry-cdn.js:2516:56)
    at Promise (http://localhost:8000/arcs/shell/build/worker-entry-cdn.js:1950:24)
    at new Promise (<anonymous>)
    at Object.mapHandle (http://localhost:8000/arcs/shell/build/worker-entry-cdn.js:1949:16)
    at Multiplexer.setViews (http://localhost:8000/arcs/shell/artifacts/Common/source/Multiplexer.js:33:49)
    at <anonymous>
```

If you need more detailed debugging to identify involved recipes or otherwise let me know.

**Comment by shaper** [comment]
I think this is obsolete.
